# Generated by Django 2.2.7 on 2019-11-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('box_num', models.IntegerField(primary_key=True, serialize=False)),
                ('box_size', models.CharField(blank=True, max_length=10, null=True)),
                ('box_price', models.IntegerField(blank=True, null=True)),
                ('box_isuse', models.CharField(blank=True, max_length=5, null=True)),
                ('box_sdate', models.DateTimeField(blank=True, null=True)),
                ('box_pwd', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'box',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_num', models.AutoField(primary_key=True, serialize=False)),
                ('log_sdate', models.DateTimeField(blank=True, null=True)),
                ('log_edate', models.DateTimeField(blank=True, null=True)),
                ('log_pay', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log',
                'managed': False,
            },
        ),
    ]
